# Generated by Django 5.2.17 on 2026-08-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='fornecedores', to='core.categoria'),
        ),
    ]
