# Generated by Django 5.2.17 on 2026-08-27 22:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo_limite', models.DateTimeField()),
                ('status', models.CharField(choices=[('aberta', 'Aberta (aguardando respostas)'), ('parcial', 'Parcial (algumas respostas)'), ('fechada', 'Fechada (prazo expirado)'), ('cancelada', 'Cancelada pelo cliente'), ('pedido_disparado', 'Pedido(s) disparado(s)')], default='aberta', max_length=20)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('fechada_em', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='CotacaoTokenFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usado_em', models.DateTimeField(blank=True, null=True)),
                ('cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_fornecedor', to='cotacoes.cotacao')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_cotacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemCotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_nome', models.CharField(max_length=200)),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unidade', models.CharField(default='un', max_length=20)),
                ('descricao', models.TextField(blank=True, default='')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_cotacao', to='core.categoria')),
                ('cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='cotacoes.cotacao')),
            ],
            options={
                'verbose_name': 'Item da Cotação',
                'verbose_name_plural': 'Itens da Cotação',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enviado', 'Enviado ao fornecedor'), ('confirmado', 'Confirmado pelo fornecedor'), ('em_producao', 'Em produção'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='enviado', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cotacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='cotacoes.cotacao')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_recebidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RespostaFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('prazo_entrega_dias', models.PositiveIntegerField(default=0, help_text='Dias úteis para entrega após confirmação')),
                ('marca', models.CharField(blank=True, default='', max_length=100)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas_cotacao', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_fornecedor', to='cotacoes.itemcotacao')),
            ],
            options={
                'verbose_name': 'Resposta do Fornecedor',
                'verbose_name_plural': 'Respostas dos Fornecedores',
                'ordering': ['preco_unitario'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('item_cotacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='cotacoes.itemcotacao')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='cotacoes.pedido')),
                ('resposta_vencedora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='cotacoes.respostafornecedor')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
        migrations.AddIndex(
            model_name='cotacao',
            index=models.Index(fields=['cliente', 'status'], name='cotacoes_co_cliente_70535d_idx'),
        ),
        migrations.AddIndex(
            model_name='cotacao',
            index=models.Index(fields=['status', 'prazo_limite'], name='cotacoes_co_status_03c0cc_idx'),
        ),
        migrations.AddIndex(
            model_name='cotacaotokenfornecedor',
            index=models.Index(fields=['cotacao', 'fornecedor'], name='cotacoes_co_cotacao_35a310_idx'),
        ),
        migrations.AddIndex(
            model_name='cotacaotokenfornecedor',
            index=models.Index(fields=['token_hash'], name='cotacoes_co_token_h_a0c0c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='respostafornecedor',
            unique_together={('item', 'fornecedor')},
        ),
    ]
